<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\RKC.Nestize.Contracts\RKC.Nestize.Contracts.csproj" />
    <ProjectReference Include="..\RKC.Nestize.Entity\RKC.Nestize.Entity.csproj" />
    <ProjectReference Include="..\RKC.Nestize.Lib\RKC.Nestize.Lib.csproj" />
    <ProjectReference Include="..\..\Contacts\RKC.Contacts.Contracts\RKC.Contacts.Contracts.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
